import Head from "next/head"
import React from "react"

import Login from "./login"

export default function Home() {
  return (
    <>
      <Head>
        <title>Eutools</title>
        <meta name="description" content="Generated by create next app" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Login />
      </main>
    </>
  )
}
